apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      run: price-shopping
  template:
    metadata:
      labels:
        run: price-shopping
    spec:
      containers:
      - name: price-shopping
        image: baseline
        resources:
          requests:
            cpu: "200m"
            memory: "50Mi"
        ports:
        - containerPort: 8521
          name: price-shopping
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: price-shopping
        readinessProbe:
          httpGet:
            path: /
            port: price-shopping

