apiVersion: apps/v1
kind: Deployment
metadata:
  name: jg
spec:
  replicas: 2
  selector:
    matchLabels:
      run: jg
  template:
    metadata:
      labels:
        run: jg
    spec:
      containers:
      - name: jg
        image: baseline
        resources:
          requests:
            cpu: "200m"
            memory: "50Mi"
        ports:
        - containerPort: 8521
          name: jg
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: jg
        readinessProbe:
          httpGet:
            path: /
            port: jg

