apiVersion: v1
kind: Service
metadata:
  name: price-shopping
  labels:
    run: price-shopping
spec:
  selector:
    run: price-shopping
  ports:
    - name: web
      port: 80
      targetPort: price-shopping
